### PR TITLE
Automatic unit conversion using pint

### PR DESCRIPTION
**Pull request by BenPortner**
This PR introduces a new class `PintParameterSet`, which can solve formulas including units.

The unit parsing is handled by the external `pint` package, which is included as an *optional* dependency. To activate, users will have to do `pip install bw2parameters[pint]`. The new class should not break any existing functionality. Tests for the new class have been included and should be skipped if pint is not installed in the environment. Calls to `evaluate` return a dictionary with `pint.Quantity` values.

# Example
```python
    from bw2parameters import PintParameterSet
    ps = PintParameterSet({
        'A': {'formula': '1 m'},
        'B': {'formula': 'A + 200 mm'},
        'C': {'formula': 'B * kg/m'},
        'D': {'formula': 'A * B * C'},
    })
    ps.evaluate() 
# {'A': 1 <Unit('meter')>,
# 'B': 1.2 <Unit('meter')>,
# 'C': 1.2 <Unit('kilogram')>,
# 'D': 1.44 <Unit('kilogram * meter ** 2')>}
```

### CODE REVIEW

**Comment by tngTUDOR** [comment]
👋 @BenPortner 

It would be great if you add to the `docs` of the package an example that uses the pint based parameters you're adding here.

**Comment by tngTUDOR** [comment]
The pipelines are failing here with py27
@cmutel , would it be safe to remove the py27 support of brightway2-parameters ? I would advice in favor (of removing py27 support) because:

+ There would be  a version bump when adding this feature, making it clear that after a certain version, we don't support py27 anymore
+ all other py3x envs pass the tests

**Comment by tngTUDOR** [comment]
> The pipelines are failing here with py27 @cmutel , would it be safe to remove the py27 support of brightway2-parameters ? I would advice in favor (of removing py27 support) because:
> 
> * There would be  a version bump when adding this feature, making it clear that after a certain version, we don't support py27 anymore
> * all other py3x envs pass the tests

also, pint seems to be "python 3.8+" compatible, so maybe, we shouldn't even be testing against python<3.8

**Comment by BenPortner** [comment]
@tngTUDOR: Updated the docs.
@cmutel: waiting for your approval to drop v2.7 support

**Comment by cmutel** [comment]
@BenPortner Awesome work! Dropping 2.7 is fine.

**Comment by BenPortner** [comment]
@cmutel @tngTUDOR @michaelweinold 
ready to merge in my opinion. please review below changes and give me feedback. 

open question:
- can appveyor setup be removed as well?
- who will publish on pypi / conda-forge? if you give me access i can handle this.

change log:
- dropped py27 support
- because this is a breaking change, I bumped the version to 1.0.0
- checked in .gitignore
- removed legacy .hgignore and bitbucket pipeline setup
- fixed the setup.py so that the description is properly shown on pypi

**Comment by cmutel** [comment]
Hey, it looks like you are done making changes for now, but could you quickly confirm?

> can appveyor setup be removed as well?

Yes, Github Actions builds on all OSes and it is simpler to maintain one CI.

> who will publish on pypi / conda-forge? if you give me access i can handle this.

Conda-forge will generate update PRs automatically, and the maintainers will be notified, once we release on pypi.

I can make you a collaborator on PyPI if you tell me your username or associated email.

**Comment by BenPortner** [comment]
> Hey, it looks like you are done making changes for now, but could you quickly confirm?

Confirmed!

> > can appveyor setup be removed as well?
> 
> Yes, Github Actions builds on all OSes and it is simpler to maintain one CI.

Done. 
 
> > who will publish on pypi / conda-forge? if you give me access i can handle this.
> 
> Conda-forge will generate update PRs automatically, and the maintainers will be notified, once we release on pypi.
> 
> I can make you a collaborator on PyPI if you tell me your username or associated email.

I would like to be a collaborator. This is me: https://pypi.org/user/BenPortner/

**Comment by BenPortner** [comment]
@cmutel @tngTUDOR @michaelweinold

I had to fix `PintInterpreter.eval()`. The following now works:

```python
from bw2parameters import PintInterpreter
i = PintInterpreter()
i("1 kg + 200 g")
# 1.2 kg
```

**Comment by BenPortner** [comment]
Minor changes:
- replaced `utils.get_symbols` with `Interpreter.get_unknown_symbols`
- replaced `utils.EXISTING_SYMBOLS` with `Interpreter.BUILTIN_symbols`
- `Interpreter.eval()` has new parameter `known_symbols` which can be used to pass temporary symbol definitions (i.e. the symbols are not permanently added to the symtable)

**Review by cmutel — COMMENTED** [review]
@BenPortner I feel like making pint optional might be the wrong choice. It is adding a lot of complexity, and isn't a heavy dependency at all (and I think it will soon because a base dependency of Brightway). What do you think about just requiring it? I am ok with paying a small price at interpreter startup.

**Pull request merged**
